# Assigment 4

This assigment will be graded if everything works well. I will run the script as once and everything should be done without errors and mistakes. I should be able to run your scripts in my computer and get all the results. **USE RELATIVE PATHS**. An error or exception or anything that breaks the code will means NO GRADE (0). Additionally, you are not able to modify any file handly. It also means NO GRADE (0). Comment everything you think will help others read your script. We expect 0 errors using GitHub. Everything will be graded!

**ASK EVERYTHING! WE ARE HERE TO HELP YOU!**

In this path **..\_data\sbs\B_RawData\bancos** you will find scraped data from [this link](https://www.sbs.gob.pe/app/pp/EstadisticasSAEEPortal/Paginas/TIActivaTipoCreditoEmpresa.aspx?tip=B). We get all the information of the last available day of every each month.

1. Import all the data and generate a column named as `date_info` that should have the day to information corresponds.
2. Append all this datasets and generate a unique dataframe. This newdataset should have information at `rate interest` and `date` level. The columns should be the name of the banks. Be careful since not all the excel files have the same format. **It is totally prohibited to manipulate manually the excel files. This kind of action means NO GRADE on this project.**
3. What are the top 5 banks each year with the highest interest rate at `Préstamos hipotecarios para vivienda`, `Consumo -
Tarjetas de Crédito`. Present a dataframe with these variables: `year`, `rate_concept`, `banks`, `rate_value`.
4. We want to save this dataset in the folder **_output/sbs/group_#**, but we want to save a file per bank. We want to have the information disaggregated at the bank level. Please, save your files with the name of the bank. Avoid blank spaces and use only lowercase letters. Generate the folder of your group using python code. **Hint: os library**

### Answers:

In [45]:
import pandas as pd
import numpy as np
import os
from datetime import datetime

#### Answer 1:

In [223]:
xlsx_files = [*map(lambda x: x[12:-5], os.listdir('../../_data/sbs/B_RawData/bancos'))]

In [289]:
d = {}
for x in xlsx_files:
    d["table_"+x] = pd.read_excel(r'../../_data/sbs/B_RawData/bancos/table_clean_'+x+'.xlsx')
    d["table_"+x]["date_info"] = datetime.strptime(x, "%d_%m_%Y").date()

#### Answer 2:

In [292]:
# Identificar patrón en el formato de los dataframes
df = pd.DataFrame(columns = ["SegundaColumna", "Fecha"])
i = 0

for x in xlsx_files:
    df.loc[i,"SegundaColumna"] = d["table_"+x].columns[1]
    df.loc[i,"Fecha"] = d["table_"+x].iloc[0,-1]
    i += 1

df = df.sort_values("Fecha").reset_index()

for x in range(np.shape(df)[0]):
    print(f'Primera columna: [{df.loc[x,"SegundaColumna"]}] y Fecha: [{df.loc[x,"Fecha"]}]')

Primera columna: [BBVA] y Fecha: [2001-03-31]
Primera columna: [COMERCIAL] y Fecha: [2002-09-30]
Primera columna: [COMERCIAL] y Fecha: [2002-10-31]
Primera columna: [COMERCIAL] y Fecha: [2002-11-29]
Primera columna: [COMERCIAL] y Fecha: [2002-12-31]
Primera columna: [COMERCIAL] y Fecha: [2003-01-31]
Primera columna: [COMERCIAL] y Fecha: [2003-02-28]
Primera columna: [COMERCIAL] y Fecha: [2003-03-31]
Primera columna: [COMERCIAL] y Fecha: [2003-04-30]
Primera columna: [COMERCIAL] y Fecha: [2003-05-30]
Primera columna: [COMERCIAL] y Fecha: [2003-06-30]
Primera columna: [COMERCIAL] y Fecha: [2003-07-31]
Primera columna: [COMERCIAL] y Fecha: [2003-08-29]
Primera columna: [COMERCIAL] y Fecha: [2003-09-30]
Primera columna: [COMERCIAL] y Fecha: [2003-10-31]
Primera columna: [COMERCIAL] y Fecha: [2003-11-28]
Primera columna: [COMERCIAL] y Fecha: [2003-12-31]
Primera columna: [COMERCIAL] y Fecha: [2004-01-29]
Primera columna: [COMERCIAL] y Fecha: [2004-02-26]
Primera columna: [COMERCIAL] y Fecha: [2004-03-31]
Primera columna: [COMERCIAL] y Fecha: [2004-04-30]
Primera columna: [COMERCIAL] y Fecha: [2004-05-31]
Primera columna: [COMERCIAL] y Fecha: [2004-06-30]
Primera columna: [COMERCIAL] y Fecha: [2004-07-30]
Primera columna: [COMERCIAL] y Fecha: [2004-08-31]
Primera columna: [COMERCIAL] y Fecha: [2004-09-30]
Primera columna: [COMERCIAL] y Fecha: [2004-10-29]
Primera columna: [COMERCIAL] y Fecha: [2004-11-30]
Primera columna: [COMERCIAL] y Fecha: [2004-12-31]
Primera columna: [COMERCIAL] y Fecha: [2005-01-31]
Primera columna: [COMERCIAL] y Fecha: [2005-02-28]
Primera columna: [COMERCIAL] y Fecha: [2005-03-31]
Primera columna: [COMERCIAL] y Fecha: [2005-04-29]
Primera columna: [COMERCIAL] y Fecha: [2005-05-31]
Primera columna: [COMERCIAL] y Fecha: [2005-06-30]
Primera columna: [COMERCIAL] y Fecha: [2005-07-27]
Primera columna: [COMERCIAL] y Fecha: [2005-08-31]
Primera columna: [COMERCIAL] y Fecha: [2005-09-30]
Primera columna: [COMERCIAL] y Fecha: [2005-10-31]
Primera columna: [COMERCIAL] y Fecha: [2005-11-29]
Primera columna: [COMERCIAL] y Fecha: [2005-12-30]
Primera columna: [COMERCIAL] y Fecha: [2006-01-31]
Primera columna: [COMERCIAL] y Fecha: [2006-02-28]
Primera columna: [COMERCIAL] y Fecha: [2006-03-31]
Primera columna: [COMERCIAL] y Fecha: [2006-04-28]
Primera columna: [COMERCIAL] y Fecha: [2006-05-31]
Primera columna: [COMERCIAL] y Fecha: [2006-06-30]
Primera columna: [COMERCIAL] y Fecha: [2006-07-31]
Primera columna: [COMERCIAL] y Fecha: [2006-08-31]
Primera columna: [COMERCIAL] y Fecha: [2006-09-29]
Primera columna: [COMERCIAL] y Fecha: [2006-10-31]
Primera columna: [COMERCIAL] y Fecha: [2006-11-30]
Primera columna: [COMERCIAL] y Fecha: [2006-12-29]
Primera columna: [COMERCIAL] y Fecha: [2007-01-31]
Primera columna: [COMERCIAL] y Fecha: [2007-02-28]
Primera columna: [COMERCIAL] y Fecha: [2007-03-30]
Primera columna: [COMERCIAL] y Fecha: [2007-04-30]
Primera columna: [COMERCIAL] y Fecha: [2007-05-31]
Primera columna: [COMERCIAL] y Fecha: [2007-06-28]
Primera columna: [COMERCIAL] y Fecha: [2007-07-31]
Primera columna: [COMERCIAL] y Fecha: [2007-08-31]
Primera columna: [COMERCIAL] y Fecha: [2007-09-28]
Primera columna: [COMERCIAL] y Fecha: [2007-10-31]
Primera columna: [COMERCIAL] y Fecha: [2007-11-30]
Primera columna: [COMERCIAL] y Fecha: [2007-12-31]
Primera columna: [COMERCIAL] y Fecha: [2008-01-31]
Primera columna: [COMERCIAL] y Fecha: [2008-02-29]
Primera columna: [COMERCIAL] y Fecha: [2008-03-31]
Primera columna: [COMERCIAL] y Fecha: [2008-04-30]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2008-05-30]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2008-06-30]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2008-07-31]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2008-08-29]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2008-09-30]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2008-10-31]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2008-11-28]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2008-12-30]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2009-01-30]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2009-02-27]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2009-03-31]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2009-04-30]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2009-05-29]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2009-06-30]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2009-07-31]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2009-08-31]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2009-09-30]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2009-10-30]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2009-11-30]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2009-12-30]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2010-01-29]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2010-02-26]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2010-03-31]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2010-04-30]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2010-05-31]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2010-06-30]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2010-07-27]
Primera columna: [CRÉDITOS COMERCIALES] y Fecha: [2010-08-31]
Primera columna: [Continental] y Fecha: [2010-09-30]
Primera columna: [Continental] y Fecha: [2010-10-29]
Primera columna: [Continental] y Fecha: [2010-11-30]
Primera columna: [Continental] y Fecha: [2010-12-31]
Primera columna: [Continental] y Fecha: [2011-01-31]
Primera columna: [Continental] y Fecha: [2011-02-28]
Primera columna: [Continental] y Fecha: [2011-03-31]
Primera columna: [Continental] y Fecha: [2011-04-29]
Primera columna: [Continental] y Fecha: [2011-05-31]
Primera columna: [Continental] y Fecha: [2011-06-30]
Primera columna: [Continental] y Fecha: [2011-07-27]
Primera columna: [Continental] y Fecha: [2011-08-31]
Primera columna: [Continental] y Fecha: [2011-09-30]
Primera columna: [Continental] y Fecha: [2011-10-28]
Primera columna: [Continental] y Fecha: [2011-11-30]
Primera columna: [Continental] y Fecha: [2011-12-30]
Primera columna: [Continental] y Fecha: [2012-01-31]
Primera columna: [Continental] y Fecha: [2012-02-29]
Primera columna: [Continental] y Fecha: [2012-03-30]
Primera columna: [Continental] y Fecha: [2012-04-30]
Primera columna: [Continental] y Fecha: [2012-05-31]
Primera columna: [Continental] y Fecha: [2012-06-28]
Primera columna: [Continental] y Fecha: [2012-07-31]
Primera columna: [Continental] y Fecha: [2012-08-29]
Primera columna: [Continental] y Fecha: [2012-09-28]
Primera columna: [Continental] y Fecha: [2012-10-31]
Primera columna: [Continental] y Fecha: [2012-11-30]
Primera columna: [Continental] y Fecha: [2012-12-28]
Primera columna: [Continental] y Fecha: [2013-01-31]
Primera columna: [Continental] y Fecha: [2013-02-28]
Primera columna: [Continental] y Fecha: [2013-03-27]
Primera columna: [Continental] y Fecha: [2013-04-30]
Primera columna: [Continental] y Fecha: [2013-05-31]
Primera columna: [Continental] y Fecha: [2013-06-28]
Primera columna: [Continental] y Fecha: [2013-07-31]
Primera columna: [Continental] y Fecha: [2013-08-29]
Primera columna: [Continental] y Fecha: [2013-09-30]
Primera columna: [Continental] y Fecha: [2013-10-31]
Primera columna: [Continental] y Fecha: [2013-11-29]
Primera columna: [Continental] y Fecha: [2013-12-30]
Primera columna: [Continental] y Fecha: [2014-01-31]
Primera columna: [Continental] y Fecha: [2014-02-28]
Primera columna: [Continental] y Fecha: [2014-03-31]
Primera columna: [Continental] y Fecha: [2014-04-30]
Primera columna: [Continental] y Fecha: [2014-05-30]
Primera columna: [Continental] y Fecha: [2014-06-30]
Primera columna: [Continental] y Fecha: [2014-07-31]
Primera columna: [Continental] y Fecha: [2014-08-29]
Primera columna: [Continental] y Fecha: [2014-09-30]
Primera columna: [Continental] y Fecha: [2014-10-31]
Primera columna: [Continental] y Fecha: [2014-11-28]
Primera columna: [Continental] y Fecha: [2014-12-31]
Primera columna: [Continental] y Fecha: [2015-01-30]
Primera columna: [Continental] y Fecha: [2015-02-27]
Primera columna: [Continental] y Fecha: [2015-03-31]
Primera columna: [Continental] y Fecha: [2015-04-30]
Primera columna: [Continental] y Fecha: [2015-05-29]
Primera columna: [Continental] y Fecha: [2015-06-30]
Primera columna: [Continental] y Fecha: [2015-07-31]
Primera columna: [Continental] y Fecha: [2015-08-31]
Primera columna: [Continental] y Fecha: [2015-09-30]
Primera columna: [Continental] y Fecha: [2015-10-30]
Primera columna: [Continental] y Fecha: [2015-11-30]
Primera columna: [Continental] y Fecha: [2015-12-31]
Primera columna: [Continental] y Fecha: [2016-01-29]
Primera columna: [Continental] y Fecha: [2016-02-29]
Primera columna: [Continental] y Fecha: [2016-03-31]
Primera columna: [Continental] y Fecha: [2016-04-29]
Primera columna: [Continental] y Fecha: [2016-05-31]
Primera columna: [Continental] y Fecha: [2016-06-30]
Primera columna: [Continental] y Fecha: [2016-07-27]
Primera columna: [Continental] y Fecha: [2016-08-31]
Primera columna: [Continental] y Fecha: [2016-09-30]
Primera columna: [Continental] y Fecha: [2016-10-31]
Primera columna: [Continental] y Fecha: [2016-11-30]
Primera columna: [Continental] y Fecha: [2016-12-30]
Primera columna: [Continental] y Fecha: [2017-01-31]
Primera columna: [Continental] y Fecha: [2017-02-28]
Primera columna: [Continental] y Fecha: [2017-03-31]
Primera columna: [Continental] y Fecha: [2017-04-28]
Primera columna: [Continental] y Fecha: [2017-05-31]
Primera columna: [Continental] y Fecha: [2017-06-28]
Primera columna: [Continental] y Fecha: [2017-07-31]
Primera columna: [Continental] y Fecha: [2017-08-31]
Primera columna: [Continental] y Fecha: [2017-09-29]
Primera columna: [Continental] y Fecha: [2017-10-31]
Primera columna: [Continental] y Fecha: [2017-11-30]
Primera columna: [Continental] y Fecha: [2017-12-29]
Primera columna: [Continental] y Fecha: [2018-01-31]
Primera columna: [Continental] y Fecha: [2018-02-28]
Primera columna: [Continental] y Fecha: [2018-03-28]
Primera columna: [Continental] y Fecha: [2018-04-30]
Primera columna: [Continental] y Fecha: [2018-05-31]
Primera columna: [Continental] y Fecha: [2018-06-28]
Primera columna: [Continental] y Fecha: [2018-07-31]
Primera columna: [Continental] y Fecha: [2018-08-29]
Primera columna: [Continental] y Fecha: [2018-09-28]
Primera columna: [Continental] y Fecha: [2018-10-31]
Primera columna: [Continental] y Fecha: [2018-11-30]
Primera columna: [Continental] y Fecha: [2018-12-31]
Primera columna: [Continental] y Fecha: [2019-01-31]
Primera columna: [Continental] y Fecha: [2019-02-28]
Primera columna: [Continental] y Fecha: [2019-03-28]
Primera columna: [Continental] y Fecha: [2019-04-30]
Primera columna: [Continental] y Fecha: [2019-05-31]
Primera columna: [BBVA] y Fecha: [2019-06-28]
Primera columna: [BBVA] y Fecha: [2019-07-31]
Primera columna: [BBVA] y Fecha: [2019-08-27]
Primera columna: [BBVA] y Fecha: [2019-09-30]
Primera columna: [BBVA] y Fecha: [2019-10-30]
Primera columna: [BBVA] y Fecha: [2019-11-29]
Primera columna: [BBVA] y Fecha: [2019-12-31]
Primera columna: [BBVA] y Fecha: [2020-01-31]
Primera columna: [BBVA] y Fecha: [2020-02-28]
Primera columna: [BBVA] y Fecha: [2020-03-31]
Primera columna: [BBVA] y Fecha: [2020-04-30]
Primera columna: [BBVA] y Fecha: [2020-05-29]
Primera columna: [BBVA] y Fecha: [2020-06-30]
Primera columna: [BBVA] y Fecha: [2020-07-31]
Primera columna: [BBVA] y Fecha: [2020-08-31]
Primera columna: [BBVA] y Fecha: [2020-09-30]
Primera columna: [BBVA] y Fecha: [2020-10-30]
Primera columna: [BBVA] y Fecha: [2020-11-30]
Primera columna: [BBVA] y Fecha: [2020-12-31]
Primera columna: [BBVA] y Fecha: [2021-01-29]
Primera columna: [BBVA] y Fecha: [2021-02-26]
Primera columna: [BBVA] y Fecha: [2021-03-31]
Primera columna: [BBVA] y Fecha: [2021-04-30]
Primera columna: [BBVA] y Fecha: [2021-05-31]
Primera columna: [BBVA] y Fecha: [2021-06-30]
Primera columna: [BBVA] y Fecha: [2021-07-30]
Primera columna: [BBVA] y Fecha: [2021-08-31]
Primera columna: [BBVA] y Fecha: [2021-09-30]
Primera columna: [BBVA] y Fecha: [2021-10-29]
Primera columna: [BBVA] y Fecha: [2021-11-30]
Primera columna: [BBVA] y Fecha: [2021-12-31]
Primera columna: [BBVA] y Fecha: [2022-01-31]
Primera columna: [BBVA] y Fecha: [2022-02-28]
Primera columna: [BBVA] y Fecha: [2022-03-31]
Primera columna: [BBVA] y Fecha: [2022-04-29]
Primera columna: [BBVA] y Fecha: [2022-05-31]
Primera columna: [BBVA] y Fecha: [2022-06-30]
Primera columna: [BBVA] y Fecha: [2022-07-27]
Primera columna: [BBVA] y Fecha: [2022-08-31]

In [294]:
for x in xlsx_files:
    if datetime.strptime("30_9_2010", "%d_%m_%Y").date() > datetime.strptime(x, "%d_%m_%Y").date() > datetime.strptime("31_3_2001", "%d_%m_%Y").date():
        d["table_"+x].columns = ['Tasa Anual (%)']+list(d["table_"+x].iloc[1])[1:]
        d["table_"+x] = d["table_"+x].loc[2:,:]
        d["table_"+x] = d["table_"+x].transpose().reset_index()
        d["table_"+x].columns = list(d["table_"+x].iloc[0])
        d["table_"+x] = d["table_"+x].iloc[1:-1,:]
        d["table_"+x]["date_info"] = datetime.strptime(x, "%d_%m_%Y").date()
        # Solo falta corregir nombres de bancos
    else:
        d["table_"+x].columns = [d["table_"+x].columns[0]]+[*map(lambda k: k.upper(), d["table_"+x].columns[1:-2])]+d["table_"+x].columns[-2:].tolist()
        d["table_"+x].rename(columns = {"CONTINENTAL": "BBVA", "BANCO GNB": "GNB"}, inplace = True)

In [ ]:
# Tomar en consideración que el banco Financiero se convierte en Pichincha?
# Tomar en consideración que el banco Azteca se convierte en Alfin?
# Retirar posibles "  *"

In [295]:
print(d["table_31_3_2001"].columns)
print(d["table_31_5_2005"].columns)
print(d["table_31_3_2009"].columns)
print(d["table_30_6_2010"].columns)
print(d["table_30_4_2012"].columns)
print(d["table_30_1_2015"].columns)
print(d["table_31_5_2016"].columns)
print(d["table_28_2_2019"].columns)
print(d["table_28_6_2019"].columns)
print(d["table_31_12_2020"].columns)
print(d["table_30_7_2021"].columns)
print(d["table_31_8_2022"].columns)

Index(['Tasa Anual (%)', 'BBVA', 'COMERCIO', 'CRÉDITO', 'PICHINCHA', 'BIF',
       'SCOTIABANK', 'CITIBANK', 'INTERBANK', 'MIBANCO', 'GNB', 'FALABELLA',
       'SANTANDER', 'RIPLEY', 'ALFIN', 'ICBC', 'BANK OF CHINA', 'Promedio',
       'date_info'],
      dtype='object')
Index(['Tasa Anual (%)', 'TRABAJO', 'BBVA', 'BANCO DE COMERCIO',
       'BANCO DE CREDITO', 'BANCO PICHINCHA', 'BANBIF', 'STANDARD CHARTERED',
       'BANCO SUDAMERICANO', 'WIESE SUDAMERIS', 'BANK BOSTON',
       'BNP PARIBAS EL', 'CITIBANK DEL PERU', 'INTERBANK', 'MIBANCO',
       'Promedio del Sistema', 'date_info'],
      dtype='object')
Index([      'Tasa Anual (%)',                 'BBVA',    'BANCO DE COMERCIO',
           'BANCO DE CREDITO',      'BANCO PICHINCHA',               'BANBIF',
            'SCOTIABANK PERU',    'CITIBANK DEL PERU',            'INTERBANK',
                    'MIBANCO',                 'HSBC',      'BANCO FALABELLA',
             'SANTANDER PERU',         'BANCO RIPLEY',          'ALFIN BANCO',
         'DEUTSCHE BANK PERU', 'Promedio del Sistema',                    nan,
                  'date_info'],
      dtype='object')
Index([      'Tasa Anual (%)',                 'BBVA',    'BANCO DE COMERCIO',
           'BANCO DE CREDITO',      'BANCO PICHINCHA',               'BANBIF',
            'SCOTIABANK PERU',    'CITIBANK DEL PERU',            'INTERBANK',
                    'MIBANCO',                 'HSBC',      'BANCO FALABELLA',
             'SANTANDER PERU',         'BANCO RIPLEY',          'ALFIN BANCO',
         'DEUTSCHE BANK PERU', 'Promedio del Sistema',                    nan,
                  'date_info'],
      dtype='object')
Index(['Tasa Anual (%)', 'BBVA', 'COMERCIO', 'CRÉDITO', 'FINANCIERO', 'BIF',
       'SCOTIABANK', 'CITIBANK', 'INTERBANK', 'MIBANCO', 'HSBC', 'FALABELLA',
       'SANTANDER', 'RIPLEY', 'AZTECA  *', 'DEUTSCHE', 'Promedio',
       'date_info'],
      dtype='object')
Index(['Tasa Anual (%)', 'BBVA', 'COMERCIO', 'CRÉDITO', 'FINANCIERO', 'BIF',
       'SCOTIABANK', 'CITIBANK', 'INTERBANK', 'MIBANCO', 'GNB', 'FALABELLA',
       'SANTANDER', 'RIPLEY', 'AZTECA', 'DEUTSCHE', 'CENCOSUD', 'ICBC',
       'Promedio', 'date_info'],
      dtype='object')
Index(['Tasa Anual (%)', 'BBVA', 'COMERCIO', 'CRÉDITO', 'FINANCIERO', 'BIF',
       'SCOTIABANK', 'CITIBANK', 'INTERBANK', 'MIBANCO', 'GNB', 'FALABELLA',
       'SANTANDER', 'RIPLEY', 'AZTECA', 'DEUTSCHE', 'CAT', 'ICBC', 'Promedio',
       'date_info'],
      dtype='object')
Index(['Tasa Anual (%)', 'BBVA', 'COMERCIO', 'CRÉDITO', 'PICHINCHA', 'BIF',
       'SCOTIABANK', 'CITIBANK', 'INTERBANK', 'MIBANCO', 'GNB', 'FALABELLA',
       'SANTANDER', 'RIPLEY', 'AZTECA', 'CAT', 'ICBC', 'Promedio',
       'date_info'],
      dtype='object')
Index(['Tasa Anual (%)', 'BBVA', 'COMERCIO', 'CRÉDITO', 'PICHINCHA', 'BIF',
       'SCOTIABANK', 'CITIBANK', 'INTERBANK', 'MIBANCO', 'GNB', 'FALABELLA',
       'SANTANDER', 'RIPLEY', 'AZTECA', 'ICBC', 'Promedio', 'date_info'],
      dtype='object')
Index(['Tasa Anual (%)', 'BBVA', 'COMERCIO', 'CRÉDITO', 'PICHINCHA', 'BIF',
       'SCOTIABANK', 'CITIBANK', 'INTERBANK', 'MIBANCO', 'GNB', 'FALABELLA',
       'SANTANDER', 'RIPLEY', 'AZTECA', 'ICBC', 'BANK OF CHINA', 'Promedio',
       'date_info'],
      dtype='object')
Index(['Tasa Anual (%)', 'BBVA', 'COMERCIO', 'CRÉDITO', 'PICHINCHA', 'BIF',
       'SCOTIABANK', 'CITIBANK', 'INTERBANK', 'MIBANCO', 'GNB', 'FALABELLA',
       'SANTANDER', 'RIPLEY', 'AZTECA', 'ICBC', 'BANK OF CHINA', 'Promedio',
       'date_info'],
      dtype='object')
Index(['Tasa Anual (%)', 'BBVA', 'COMERCIO', 'CRÉDITO', 'PICHINCHA', 'BIF',
       'SCOTIABANK', 'CITIBANK', 'INTERBANK', 'MIBANCO', 'GNB', 'FALABELLA',
       'SANTANDER', 'RIPLEY', 'ALFIN', 'ICBC', 'BANK OF CHINA', 'BCI',
       'Promedio', 'date_info'],
      dtype='object')

In [175]:
# Cuentas dentro del rango de fechas:
# Fila numero 1 debe convertirse en nombres de columna, luego Transpose
d["table_"+xlsx_files[6]].columns = ['Tasa Anual (%)']+list(d["table_"+xlsx_files[6]].iloc[1])[1:]
d["table_"+xlsx_files[6]] = d["table_"+xlsx_files[6]].loc[2:,:]
d["table_"+xlsx_files[6]] = d["table_"+xlsx_files[6]].transpose().reset_index()
d["table_"+xlsx_files[6]].columns = list(d["table_"+xlsx_files[6]].iloc[0])
d["table_"+xlsx_files[6]] = d["table_"+xlsx_files[6]].iloc[1:-1,:]
d["table_"+xlsx_files[6]]["date_info"] = datetime.strptime(xlsx_files[6], "%d_%m_%Y").date()

In [299]:
d["table_"+xlsx_files[6]]

,Tasa Anual (%),TRABAJO,BBVA,BANCO DE COMERCIO,BANCO DE CREDITO,BANCO PICHINCHA,BANBIF,STANDARD CHARTERED,BANCO SUDAMERICANO,WIESE SUDAMERIS,BANK BOSTON,BNP PARIBAS EL,CITIBANK DEL PERU,INTERBANK,MIBANCO,Promedio del Sistema,date_info
1,Avances en Cta.Corriente,-,36.64,37.62,32.14,-,23.62,-,28.48,21.85,-,-,-,64.03,-,31.71,2005-07-27
2,Sobregiros,-,46.56,138.18,37.60,-,41.61,-,62.23,44.60,-,-,77.41,5.09,-,28.67,2005-07-27
3,Dsctos. y préstamos hasta 30 días,-,8.64,36.37,5.28,14.11,16.43,-,12.54,17.69,-,-,6.00,11.06,50.00,6.11,2005-07-27
4,Dsctos. y préstamos 31 - 90 días,-,8.93,20.34,7.61,12.66,10.13,-,8.11,9.16,-,-,6.13,6.57,-,8.18,2005-07-27
5,Dsctos. y préstamos 91 - 180 días,41.00,8.72,15.63,8.89,14.63,10.16,-,11.33,6.96,-,-,8.79,6.91,49.85,8.73,2005-07-27
6,Dsctos. y préstamos 181 - 360 días,44.37,19.11,-,5.00,50.00,8.15,-,7.92,10.54,-,-,8.73,5.83,41.88,8.06,2005-07-27
7,Dsctos. y préstamos más 360 días,41.00,8.18,-,5.18,38.78,9.36,-,13.76,5.53,-,-,-,12.01,39.22,6.45,2005-07-27
8,Sobregiros,-,48.99,138.19,-,-,-,-,-,85.00,-,-,-,-,-,90.62,2005-07-27
9,Dsctos. y préstamos hasta 360 días,40.35,36.08,30.35,39.42,-,19.20,-,42.05,46.26,-,-,-,-,55.48,47.37,2005-07-27
10,Dsctos. y préstamos más 360 días,40.63,37.03,-,37.40,-,-,-,41.19,47.30,-,-,-,-,45.06,42.14,2005-07-27
11,Tarjetas de crédito abiertas4,81.88,44.27,24.02,32.17,51.11,25.00,-,25.00,31.02,-,-,59.93,39.39,-,44.15,2005-07-27
12,Tarjetas de crédito cerradas5,77.08,-,-,-,-,-,-,-,95.13,-,-,-,62.32,-,72.86,2005-07-27
13,Tarjetas de crédito,78.58,44.27,24.02,32.17,51.11,25.00,-,25.00,39.68,-,-,59.93,43.74,-,49.71,2005-07-27
14,Para préstamos menores o iguales a S/. 1800,44.10,21.66,24.90,-,-,22.31,-,26.70,77.96,-,-,-,30.07,75.57,52.97,2005-07-27
15,Para préstamos mayores a S/. 1800,41.71,19.37,16.57,19.63,24.81,22.90,-,36.34,26.30,-,-,-,27.59,62.41,42.03,2005-07-27
16,Préstamos hasta 360 días,43.23,19.53,24.17,19.63,24.81,22.89,-,30.19,53.52,-,-,-,28.45,66.66,46.30,2005-07-27
17,Para préstamos menores o iguales a S/. 1800,46.52,22.39,24.91,23.50,-,20.14,-,27.69,88.35,-,-,-,26.98,75.57,49.86,2005-07-27
18,Para préstamos mayores a S/. 1800,46.32,19.49,24.88,20.03,27.21,18.99,-,24.82,21.80,-,-,-,27.53,51.12,26.68,2005-07-27
19,Préstamos más de 360 días,46.38,19.65,24.88,20.03,27.21,19.02,-,24.95,29.41,-,-,-,27.52,51.40,27.73,2005-07-27
20,HIPOTECARIO,-,11.68,-,10.70,-,-,-,-,-,-,-,-,-,27.14,12.03,2005-07-27

In [133]:
xlsx_files[4]

'27_2_2015'